const members = [
  [
    {
      name: "王俊涵",
      avatar: "/members/teachers/wangjh.webp",
      description:
        "哈工大（深圳）学生艺术团创始人、首任团长，在校区学生工作处/团委任职期间指导艺术团蓬勃发展，曾多次带团参加深圳市各项演出、导演哈工大（深圳）各类大型晚会活动。对于本剧社的活动，王老师深度参与，帮助协调组织，提供了丰厚的精神支持并为本剧社争取到各项宝贵的物质支持。",
    },
    {
      name: "易悦",
      avatar: "/members/teachers/yiy.webp",
      description:
        "常年指导深圳市地铁集团有限公司馨星话剧社排演话剧，导演了《雷雨》、《日出》、《哈姆雷特》、《生死场》、《暗恋桃花源》、《红岩》等作品，在深圳市内巡回演出，反响热烈。此外，易老师还会抽出时间，积极投身深圳各大高校艺术类社团的发展，曾指导艺术团话剧部、合唱部的演出排练，传授具体实用的经验方法，极大提升了社团同学的艺术审美和表演水平。",
    },
    {
      name: "王赋",
      avatar: "/members/teachers/wangf.webp",
      description:
        "哈工大（深圳）舞台中控老师，为剧社培养了一代代出色的灯光、音效等幕后工作人员，保障演出顺利进行。",
    },
    {
      name: "李文庆",
      avatar: "/members/teachers/liwq.webp",
      description:
        "中共党员，兰州大学艺术学院声乐专业硕士，哈工大（深圳）学生艺术团现指导老师。2017年、2018年举办个人独唱音乐会，曾获2016香港国际声乐公开赛三等奖，第十三届“青春中国”甘肃总决赛三等奖，参演纪念印度著名诗人泰戈尔诞辰150周年大型原创话剧《齐德拉》、参演《江姐》《长征组歌》《邱少云组歌》《红色恋人》等大型合唱作品。",
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "南宫灥",
          avatar: "/members/2015-2016/mayh.webp",
          word: "",
          duty: [10],
        },
        {
          mark: "小黑蛋",
          avatar: "/members/2015-2016/xiaohd.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《戏中戏中戏》剧组",
      members: [
        {
          mark: "南宫灥",
          avatar: "/members/2015-2016/mayh.webp",
          word: "",
          duty: [0, 1, 2],
        },
        {
          mark: "Job",
          avatar: "/members/2015-2016/zhoujb.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "遛鸟人",
          avatar: "/members/2015-2016/zhang-l.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "天竺姑娘",
          avatar: "/members/2015-2016/zhangxq.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "车夫一号",
          avatar: "/members/2015-2016/chenjr.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "车夫二号",
          avatar: "/members/2015-2016/chengh.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "Xia",
          avatar: "/members/2015-2016/zhangyx.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "Zoe",
          avatar: "/members/2015-2016/chenl.webp",
          word: "",
          duty: [12],
        },
      ],
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "Hanks",
          avatar: "/members/2016-2017/wangzy.webp",
          word: "",
          duty: [10],
        },
        {
          mark: "XYZ",
          avatar: "/members/2016-2017/zhaoxy.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "Ben",
          avatar: "/members/2016-2017/mamk.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《你好，打劫》剧组",
      members: [
        {
          mark: "Hanks",
          avatar: "/members/2016-2017/wangzy.webp",
          word: "",
          duty: [0],
        },
        {
          mark: "XYZ",
          avatar: "/members/2016-2017/zhaoxy.webp",
          word: "",
          duty: [2],
        },
        {
          mark: "Zhu",
          avatar: "/members/2016-2017/zhusy.webp",
          word: "",
          duty: [2],
        },
        {
          mark: "Snow",
          avatar: "/members/2016-2017/maox.webp",
          word: "",
          duty: [7],
        },
        {
          mark: "Icy",
          avatar: "/members/2016-2017/zhangj.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "Ben",
          avatar: "/members/2016-2017/mamk.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "Cruise",
          avatar: "/members/2016-2017/xiezh.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "Sunny",
          avatar: "/members/2016-2017/lix.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "Tom",
          avatar: "/members/2016-2017/caiht.webp",
          word: "",
          duty: [12],
        },
      ],
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "Snow",
          avatar: "/members/2017-2018/maox.webp",
          word: "",
          duty: [10],
        },
        {
          mark: "老陶",
          avatar: "/members/2017-2018/panyl.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《暗恋·桃花源》剧组",
      members: [
        {
          mark: "Snow",
          avatar: "/members/2017-2018/maox.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "Kun",
          avatar: "/members/2017-2018/linjk.webp",
          word: "",
          duty: [7],
        },
        {
          mark: "暗恋导演",
          avatar: "/members/2017-2018/dingwz.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "青年云之凡",
          avatar: "/members/2017-2018/liangyh.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "青年江滨柳",
          avatar: "/members/2017-2018/liyh.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "暮年云之凡",
          avatar: "/members/2017-2018/liyx.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "暮年江滨柳",
          avatar: "/members/2017-2018/lisq.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "江太太",
          avatar: "/members/2017-2018/zhangx.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "护士",
          avatar: "/members/2017-2018/zhouyl.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "护士",
          avatar: "/members/2017-2018/yanly.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "桃花源导演",
          avatar: "/members/2017-2018/wangxc.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "老陶",
          avatar: "/members/2017-2018/panyl.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "春花",
          avatar: "/members/2017-2018/wujl.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "袁老板",
          avatar: "/members/2017-2018/xuh.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "顺子",
          avatar: "/members/2017-2018/wanghy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "疯女人",
          avatar: "/members/2017-2018/duly.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 1,
      group: "月下零星",
      members: [
        {
          mark: "X",
          avatar: "/members/2017-2018/xuzr.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "R",
          avatar: "/members/2017-2018/hanrl.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "青莲居士",
          avatar: "/members/2017-2018/xulq.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "Q",
          avatar: "",
          word: "",
          duty: [12],
        },
        {
          mark: "YY",
          avatar: "",
          word: "",
          duty: [12],
        },
      ],
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "K嫂",
          avatar: "/members/2018-2019/panyl.webp",
          word: "原来，你就是我和K哥之间的那个小三儿！",
          duty: [10],
        },
        {
          mark: "剧社背后的女人",
          avatar: "/members/2018-2019/duly.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "Z",
          avatar: "/members/2018-2019/zhouyl.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《乌龙山伯爵》剧组",
      members: [
        {
          mark: "K嫂",
          avatar: "/members/2018-2019/panyl.webp",
          word: "",
          duty: [0, 2],
        },
        {
          mark: "剧社背后的女人",
          avatar: "/members/2018-2019/duly.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "Z",
          avatar: "/members/2018-2019/zhouyl.webp",
          word: "",
          duty: [0],
        },
        {
          mark: "L",
          avatar: "/members/2018-2019/liyx.webp",
          word: "",
          duty: [0],
        },
        {
          mark: "X",
          avatar: "/members/2018-2019/xuzr.webp",
          word: "",
          duty: [1],
        },
        {
          mark: "主持人",
          avatar: "/members/2018-2019/xuh.webp",
          word: "",
          duty: [6],
        },
        {
          mark: "Kun",
          avatar: "/members/2018-2019/linjk.webp",
          word: "",
          duty: [7],
        },
        {
          mark: "Y",
          avatar: "/members/2018-2019/liyh.webp",
          word: "",
          duty: [7],
        },
        {
          mark: "T",
          avatar: "/members/2018-2019/tangxh.webp",
          word: "",
          duty: [7],
        },
        {
          mark: "ZR",
          avatar: "/members/2018-2019/wangzr.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "S",
          avatar: "/members/2018-2019/shij.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "嘎嘎",
          avatar: "/members/2018-2019/guj.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "H",
          avatar: "",
          word: "",
          duty: [8],
        },
        {
          mark: "五月的玛丽莲",
          avatar: "/members/2018-2019/may.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "谢蟹",
          avatar: "/members/2018-2019/dingwz.webp",
          word: "你的眼睛就像一汪清澈的泉水，我好像站在你的鼻尖上，扎个猛子。",
          duty: [12],
        },
        {
          mark: "五月的玛丽莲",
          avatar: "/members/2018-2019/may.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "九月的玛丽莲",
          avatar: "/members/2018-2019/duanjy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "神父",
          avatar: "/members/2018-2019/yujx.webp",
          word: "你二大爷知道今天是你三十岁的生日，让我和你说一句生日快乐。",
          duty: [12],
        },
        {
          mark: "坟地保安团团长",
          avatar: "/members/2018-2019/zouql.webp",
          word: "活人是不会住在坟里滴，所以坟地才会死贵死贵滴！",
          duty: [12],
        },
        {
          mark: "邱田",
          avatar: "/members/2018-2019/yaosq.webp",
          word: "这都长毛了。。。",
          duty: [12],
        },
        {
          mark: "秘书",
          avatar: "/members/2018-2019/yuyz.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "女学生",
          avatar: "/members/2018-2019/heyp.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "K哥",
          avatar: "/members/2018-2019/lich.webp",
          word: "里面的人听着，你们已经被包围了！",
          duty: [12],
        },
        {
          mark: "活畜生",
          avatar: "/members/2018-2019/gaose.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "十三太保",
          avatar: "/members/2018-2019/zhangcx.webp",
          word: "没想到吧，哥现在保外就医！",
          duty: [12],
        },
        {
          mark: "艾伦警官",
          avatar: "/members/2018-2019/liqy.webp",
          word: "别怕，我一开枪你就低头。",
          duty: [12],
        },
        {
          mark: "镇长",
          avatar: "/members/2018-2019/xieyl.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "奔雷",
          avatar: "/members/2018-2019/xiongl.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "保安W",
          avatar: "/members/2018-2019/wanghy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "保安M",
          avatar: "",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 1,
      group: "月下零星",
      members: [
        {
          mark: "巾帼女将",
          avatar: "/members/2018-2019/zhoul.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "玛卡巴卡",
          avatar: "/members/2018-2019/wangmy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "R",
          avatar: "/members/2018-2019/hanrl.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "靖子",
          avatar: "/members/2018-2019/linxj.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "J",
          avatar: "",
          word: "",
          duty: [12],
        },
      ],
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "月半衔蝉",
          avatar: "/members/2019-2020/zhangcx.webp",
          word: "",
          duty: [10],
        },
        {
          mark: "Monica",
          avatar: "/members/2019-2020/duanjy.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "十七",
          avatar: "/members/2019-2020/yaosq.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "我在长沙三套房",
          avatar: "/members/2019-2020/xieyl.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《告白之夜2019》台前幕后",
      members: [
        {
          mark: "月半衔蝉",
          avatar: "/members/2019-2020/zhangcx.webp",
          word: "",
          duty: [0, 2, 4],
        },
        {
          mark: "总设计师",
          avatar: "/members/2019-2020/duly.webp",
          word: "",
          duty: [0],
        },
        {
          mark: "Monica",
          avatar: "/members/2019-2020/duanjy.webp",
          word: "",
          duty: [0, 5],
        },
        {
          mark: "公页",
          avatar: "/members/2019-2020/gaose.webp",
          word: "",
          duty: [6],
        },
        {
          mark: "我在长沙三套房",
          avatar: "/members/2019-2020/xieyl.webp",
          word: "",
          duty: [7],
        },
        {
          mark: "点点",
          avatar: "/members/2019-2020/luomc.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "音效师A",
          avatar: "/members/2019-2020/qianxn.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "追光者",
          avatar: "",
          word: "",
          duty: [8],
        },
      ],
    },
    {
      type: 2,
      group: "《从前有座山》剧组",
      members: [
        {
          mark: "姥姥",
          avatar: "/members/2019-2020/duanjy.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "我在长沙三套房",
          avatar: "/members/2019-2020/xieyl.webp",
          word: "",
          duty: [0],
        },
        {
          mark: "小和尚",
          avatar: "/members/2019-2020/panyl.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "老方丈",
          avatar: "/members/2019-2020/liqy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "僧侣",
          avatar: "/members/2019-2020/xuzr.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "衙役",
          avatar: "/members/2019-2020/dingwz.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "僧侣",
          avatar: "/members/2019-2020/lich.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "僧侣",
          avatar: "/members/2019-2020/zouql.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "僧侣",
          avatar: "/members/2019-2020/wut.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "刽子手",
          avatar: "/members/2019-2020/huangcj.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《金陵十三钗》剧组",
      members: [
        {
          mark: "姥姥",
          avatar: "/members/2019-2020/duanjy.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "我在长沙三套房",
          avatar: "/members/2019-2020/xieyl.webp",
          word: "",
          duty: [0],
        },
        {
          mark: "玉墨",
          avatar: "/members/2019-2020/may.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "书娟",
          avatar: "/members/2019-2020/zhouzj.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "学生",
          avatar: "/members/2019-2020/chenmq.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "红菱",
          avatar: "/members/2019-2020/zhangjs.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "怡春",
          avatar: "/members/2019-2020/wanggp.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "金喜",
          avatar: "/members/2019-2020/liua.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "小蚊子",
          avatar: "/members/2019-2020/zouzq.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "香兰",
          avatar: "/members/2019-2020/liangyb.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "豆蔻",
          avatar: "/members/2019-2020/tangxl.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《潜伏》剧组",
      members: [
        {
          mark: "月半衔蝉",
          avatar: "/members/2019-2020/zhangcx.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "王翠平",
          avatar: "/members/2019-2020/chenx.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "余则成",
          avatar: "/members/2019-2020/tanhr.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "李涯",
          avatar: "/members/2019-2020/liyh.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "吴敬中",
          avatar: "/members/2019-2020/zhaoyw.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《聂耳小提琴的前世传奇》剧组",
      members: [
        {
          mark: "张鹤",
          avatar: "/members/2019-2020/yaosq.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "聂耳",
          avatar: "/members/2019-2020/xieja.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "田汉",
          avatar: "/members/2019-2020/chenwb.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 1,
      group: "月下零星",
      members: [
        {
          mark: "靖子",
          avatar: "/members/2019-2020/linxj.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "T",
          avatar: "/members/2019-2020/tangxh.webp",
          word: "",
          duty: [12],
        },
      ],
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "源潮",
          avatar: "/members/2020-2021/chenwb.webp",
          word: "",
          duty: [10],
        },
        {
          mark: "丹三",
          avatar: "/members/2020-2021/wut.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "解犴",
          avatar: "/members/2020-2021/xieja.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "火山",
          avatar: "/members/2020-2021/huangcj.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《告白之夜2021》台前幕后",
      members: [
        {
          mark: "源潮",
          avatar: "/members/2020-2021/chenwb.webp",
          word: "",
          duty: [0, 2, 9],
        },
        {
          mark: "专业打杂",
          avatar: "/members/2020-2021/liyr.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "听雨声",
          avatar: "/members/2020-2021/man.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "灯控师",
          avatar: "/members/2020-2021/zouwx.webp",
          word: "",
          duty: [8],
        },
      ],
    },
    {
      type: 2,
      group: "《9102》剧组",
      members: [
        {
          mark: "9102-刚刚",
          avatar: "/members/2020-2021/wut.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "科学家头头",
          avatar: "/members/2020-2021/zhangyy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "科学家A",
          avatar: "/members/2020-2021/wuyx.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "科学家B",
          avatar: "/members/2020-2021/cuihx.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "蒸羊羔蒸鹿尾儿",
          avatar: "/members/2020-2021/gaoy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "8102",
          avatar: "/members/2020-2021/litj.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《压迫》剧组",
      members: [
        {
          mark: "男客",
          avatar: "/members/2020-2021/huangcj.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "女客",
          avatar: "/members/2020-2021/gaoy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "房东",
          avatar: "/members/2020-2021/wangmy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "老佣",
          avatar: "/members/2020-2021/zhangjs.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "一般路过小警察",
          avatar: "/members/2020-2021/liuxy.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《酒后》剧组",
      members: [
        {
          mark: "源潮",
          avatar: "/members/2020-2021/chenwb.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "荫棠",
          avatar: "/members/2020-2021/zhuhf.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "芷青",
          avatar: "/members/2020-2021/wangyr.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "醉酒客人",
          avatar: "/members/2020-2021/lianjs.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《金漆雕木大神龛》剧组",
      members: [
        {
          mark: "陈凡",
          avatar: "/members/2020-2021/xieja.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "陈卓",
          avatar: "/members/2020-2021/zhangwx.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "游击队员",
          avatar: "/members/2020-2021/zhangyy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "游击队员",
          avatar: "/members/2020-2021/yanxw.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《鸡兔同笼》剧组",
      members: [
        {
          mark: "女儿",
          avatar: "/members/2020-2021/wut.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "父亲",
          avatar: "/members/2020-2021/xieja.webp",
          word: "",
          duty: [0, 2, 3],
        },
      ],
    },
    {
      type: 1,
      group: "月下零星",
      members: [
        {
          mark: "K.L.K",
          avatar: "",
          word: "",
          duty: [12],
        },
      ],
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "猫",
          avatar: "/members/2021-2022/gaoy.webp",
          word: "",
          duty: [10],
        },
        {
          mark: "卡尔",
          avatar: "/members/2021-2022/zhuhf.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "W",
          avatar: "/members/2021-2022/wuyx.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《点名风波》剧组",
      members: [
        {
          mark: "猫",
          avatar: "/members/2021-2022/gaoy.webp",
          word: "",
          duty: [0, 2],
        },
        {
          mark: "如如",
          avatar: "",
          word: "",
          duty: [1],
        },
        {
          mark: "高数老师",
          avatar: "/members/2021-2022/pengty.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "萌萌",
          avatar: "",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 1,
      group: "《觉醒年代》剧组",
      members: [
        {
          mark: "猫",
          avatar: "/members/2021-2022/gaoy.webp",
          word: "",
          duty: [0, 1, 2],
        },
        {
          mark: "卡尔",
          avatar: "/members/2021-2022/zhuhf.webp",
          word: "",
          duty: [0, 3, 7],
        },
        {
          mark: "考研，考研呐！",
          avatar: "/members/2021-2022/zhangcx.webp",
          word: "",
          duty: [1, 2],
        },
        {
          mark: "陈独秀",
          avatar: "/members/2021-2022/wanghj.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "陈延年",
          avatar: "/members/2021-2022/liuyx.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "陈乔年",
          avatar: "/members/2021-2022/liydc.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "柳眉",
          avatar: "/members/2021-2022/zengzz.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "柳文耀",
          avatar: "/members/2021-2022/huangsj.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "易群先",
          avatar: "/members/2021-2022/tangyj.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 1,
      group: "《谁杀死了周日》剧组",
      members: [
        {
          mark: "猫",
          avatar: "/members/2021-2022/gaoy.webp",
          word: "",
          duty: [0, 2],
        },
        {
          mark: "源潮",
          avatar: "/members/2021-2022/chenwb.webp",
          word: "",
          duty: [9],
        },
        {
          mark: "主任",
          avatar: "/members/2021-2022/duanjy.webp",
          word: "我是死线，不是发际线！",
          duty: [12],
        },
        {
          mark: "周一很暴躁",
          avatar: "/members/2021-2022/zhangcx.webp",
          word: "血口喷人，信不信老子安排死你？！",
          duty: [12],
        },
        {
          mark: "周二在摸鱼",
          avatar: "/members/2021-2022/liuyx.webp",
          word: "提！",
          duty: [12],
        },
        {
          mark: "周三还在摸鱼",
          avatar: "/members/2021-2022/zhaokl.webp",
          word: "纲！",
          duty: [12],
        },
        {
          mark: "周四全听周五的",
          avatar: "/members/2021-2022/lijy.webp",
          word: "我。。。我听周五的。",
          duty: [12],
        },
        {
          mark: "高贵的周五",
          avatar: "/members/2021-2022/wut.webp",
          word: "嘿，您猜怎么蛰？",
          duty: [12],
        },
        {
          mark: "周六",
          avatar: "/members/2021-2022/huangsj.webp",
          word: "我还能喝！",
          duty: [12],
        },
      ],
    },
    {
      type: 1,
      group: "月下零星",
      members: [
        {
          mark: "蝶衣",
          avatar: "/members/2021-2022/litj.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "量子玫瑰",
          avatar: "/members/2021-2022/liangqy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "天降紫微星",
          avatar: "/members/2021-2022/lizw.webp",
          word: "",
          duty: [12],
        },
      ],
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "O。o？",
          avatar: "/members/2022-2023/liuyx.webp",
          word: "只要破译了密码，各位一定是前程无量，到时可别忘了提携我白小年啊，哈哈！",
          duty: [10],
        },
        {
          mark: "无雪",
          avatar: "/members/2022-2023/huangsj.webp",
          word: "俗话说得好，真金不怕火来烧！",
          duty: [11],
        },
        {
          mark: "量子玫瑰",
          avatar: "/members/2022-2023/liangqy.webp",
          word: "若是相连的民族血脉重于党派立场，我今天就不悔向你赔上这条命。",
          duty: [11],
        },
        {
          mark: "天降紫微星",
          avatar: "/members/2022-2023/lizw.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "背锅财务",
          avatar: "/members/2022-2023/zengzz.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《谁杀死了周日》剧组",
      members: [
        {
          mark: "主任",
          avatar: "/members/2022-2023/gaoy.webp",
          word: "我是死线，不是发际线！",
          duty: [0, 2],
        },
        {
          mark: "周一永远在暴躁",
          avatar: "/members/2022-2023/yaokx.webp",
          word: "血口喷人，信不信老子安排死你？！",
          duty: [12],
        },
        {
          mark: "周二在摸鱼",
          avatar: "/members/2022-2023/liuyx.webp",
          word: "提！",
          duty: [12],
        },
        {
          mark: "周三还在摸鱼",
          avatar: "/members/2022-2023/guokx.webp",
          word: "纲！",
          duty: [12],
        },
        {
          mark: "周四全听周五的",
          avatar: "/members/2022-2023/lijy.webp",
          word: "我。。。我听周五的。",
          duty: [12],
        },
        {
          mark: "高贵的周五",
          avatar: "/members/2022-2023/lizw.webp",
          word: "嘿，您猜怎么蛰？",
          duty: [12],
        },
        {
          mark: "周六",
          avatar: "/members/2022-2023/huangsj.webp",
          word: "我还能喝！",
          duty: [12],
        },
      ],
    },
    {
      type: 1,
      group: "《告白之夜2023·春》台前幕后",
      members: [
        {
          mark: "白小年",
          avatar: "/members/2022-2023/liuyx.webp",
          word: "只要破译了密码，各位一定是前程无量，到时可别忘了提携我白小年啊，哈哈！",
          duty: [0],
        },
        {
          mark: "珠海发哥",
          avatar: "/members/2022-2023/zhuhf.webp",
          word: "这个，就叫专业！",
          duty: [2, 4],
        },
        {
          mark: "背锅财务",
          avatar: "/members/2022-2023/zengzz.webp",
          word: "",
          duty: [0],
        },
        {
          mark: "自迩",
          avatar: "/members/2022-2023/dengrj.webp",
          word: "叫声学长我听下。",
          duty: [6],
        },
        {
          mark: "吴志国",
          avatar: "/members/2022-2023/huangsj.webp",
          word: "俗话说得好，真金不怕火来烧！",
          duty: [7],
        },
        {
          mark: "He",
          avatar: "/members/2022-2023/herh.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "Y",
          avatar: "/members/2022-2023/wuyx.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "X",
          avatar: "/members/2022-2023/sunx.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "小鸣小洪",
          avatar: "/members/2022-2023/hongym.webp",
          word: "",
          duty: [8],
        },
      ],
    },
    {
      type: 2,
      group: "《青铜仙鹤》剧组",
      members: [
        {
          mark: "李宁玉",
          avatar: "/members/2022-2023/liangqy.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "我秦始皇打钱！",
          avatar: "/members/2022-2023/yangqc.webp",
          word: "大争之世，列国伐交频频，强则强，弱则亡！",
          duty: [12],
        },
        {
          mark: "燕太子丹",
          avatar: "/members/2022-2023/tangbw.webp",
          word: "那六只鹤是六国，你要灭六国？！",
          duty: [12],
        },
        {
          mark: "驯禽师",
          avatar: "/members/2022-2023/huangsj.webp",
          word: "大王饶命啊大王！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《时间都去哪儿了》剧组",
      members: [
        {
          mark: "季英",
          avatar: "/members/2022-2023/lizw1.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "拖延症晚期患者",
          avatar: "/members/2022-2023/wanghj.webp",
          word: "人间不值得，我是真的狗啊！！！",
          duty: [12],
        },
        {
          mark: "阿信",
          avatar: "/members/2022-2023/help.webp",
          word: "来嘛，刷会儿~",
          duty: [12],
        },
        {
          mark: "阿博",
          avatar: "/members/2022-2023/liz.webp",
          word: "震惊！某男子一夜之间凭空多出七个孩子？",
          duty: [12],
        },
        {
          mark: "阿抖",
          avatar: "/members/2022-2023/hegf.webp",
          word: "三句话，让一个男人为我花了十八万。",
          duty: [12],
        },
        {
          mark: "emo",
          avatar: "/members/2022-2023/liuys.webp",
          word: "生而为人，我很抱歉！！！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《瞎了一只眼》剧组",
      members: [
        {
          mark: "季英",
          avatar: "/members/2022-2023/lizw1.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "仲湖",
          avatar: "/members/2022-2023/liqm.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "辛田",
          avatar: "/members/2022-2023/sunzy.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《风声》剧组",
      members: [
        {
          mark: "李宁玉",
          avatar: "/members/2022-2023/liangqy.webp",
          word: "若是相连的民族血脉重于党派立场，我今天就不悔向你赔上这条命。",
          duty: [0, 1, 3],
        },
        {
          mark: "妍姐",
          avatar: "/members/2022-2023/gaoy.webp",
          word: "",
          duty: [2],
        },
        {
          mark: "顾晓梦",
          avatar: "/members/2022-2023/tangyj.webp",
          word: "千金之身又怎么样，不照样在你这里做阶下囚么？",
          duty: [12],
        },
        {
          mark: "革命烈士",
          avatar: "",
          word: "",
          duty: [12],
        },
        {
          mark: "吴志国",
          avatar: "/members/2022-2023/huangsj.webp",
          word: "俗话说得好，真金不怕火来烧！",
          duty: [12],
        },
        {
          mark: "白小年",
          avatar: "/members/2022-2023/liuyx.webp",
          word: "只要破译了密码，各位一定是前程无量，到时可别忘了提携我白小年啊，哈哈！",
          duty: [12],
        },
        {
          mark: "金生火",
          avatar: "/members/2022-2023/liydc.webp",
          word: "我真是倒了八辈子的血霉啊，碰上这档子事！我这个龟毛处长看来是当到头了。",
          duty: [12],
        },
        {
          mark: "武田一号",
          avatar: "/members/2022-2023/pengty.webp",
          word: "全军第一处，岂容藏奸细？吴金李顾四，你们谁是匪？",
          duty: [12],
        },
        {
          mark: "武田二号",
          avatar: "/members/2022-2023/zhangcx.webp",
          word: "我输了？！！不！！！我怎么可能输！！我不会输！！",
          duty: [12],
        },
        {
          mark: "卫兵1号",
          avatar: "/members/2022-2023/hegf.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "卫兵2号",
          avatar: "/members/2022-2023/dengrj.webp",
          word: "",
          duty: [12],
        },
      ],
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "dushck",
          avatar: "/members/2023-2024/liqm.webp",
          word: "话剧社是我的心血，中间忘了，所以我们真的都是这么好的人吗？",
          duty: [10],
        },
        {
          mark: "杜子腾",
          avatar: "/members/2023-2024/help.webp",
          word: "Yes sir？你系条几？",
          duty: [11],
        },
        {
          mark: "1700Q币",
          avatar: "/members/2023-2024/hongym.webp",
          word: "我这个身份后期非常有用。",
          duty: [11],
        },
        {
          mark: "我秦始皇打钱",
          avatar: "/members/2023-2024/yangqc.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "川麻乐子人",
          avatar: "/members/2023-2024/tangbw.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《告白之夜2023·秋》台前幕后",
      members: [
        {
          mark: "dushck",
          avatar: "/members/2023-2024/liqm.webp",
          word: "话剧社是我的心血，中间忘了，所以我们真的都是这么好的人吗？",
          duty: [0, 2],
        },
        {
          mark: "珠海发哥",
          avatar: "/members/2023-2024/zhuhf.webp",
          word: "这个，就叫专业！",
          duty: [2, 9],
        },
        {
          mark: "妍姐",
          avatar: "/members/2023-2024/gaoy.webp",
          word: "",
          duty: [5],
        },
        {
          mark: "小夏",
          avatar: "/members/2023-2024/xiazt.webp",
          word: "",
          duty: [5],
        },
        {
          mark: "橘子姐",
          avatar: "/members/2023-2024/diaojy.webp",
          word: "",
          duty: [5],
        },
        {
          mark: "超级大壳",
          avatar: "/members/2023-2024/huangsm1.webp",
          word: "",
          duty: [5],
        },
        {
          mark: "过冬天",
          avatar: "/members/2023-2024/baomc.webp",
          word: "",
          duty: [5],
        },
        {
          mark: "菜菜",
          avatar: "/members/2023-2024/caidh.webp",
          word: "",
          duty: [5],
        },
        {
          mark: "一水儿",
          avatar: "/members/2023-2024/liuys.webp",
          word: "今夜星光璀璨！",
          duty: [6],
        },
        {
          mark: "场控组长",
          avatar: "/members/2023-2024/tangbw.webp",
          word: "",
          duty: [7],
        },
        {
          mark: "中控组长",
          avatar: "/members/2023-2024/yangqc.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "He",
          avatar: "/members/2023-2024/herh.webp",
          word: "",
          duty: [4, 8],
        },
        {
          mark: "灯子",
          avatar: "/members/2023-2024/wanghj.webp",
          word: "请记住，我是他爹。",
          duty: [8],
        },
        {
          mark: "Icy",
          avatar: "/members/2023-2024/chengx.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "幕后黑手",
          avatar: "/members/2023-2024/xiawj.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "源潮",
          avatar: "/members/2023-2024/chenwb.webp",
          word: "",
          duty: [9],
        },
      ],
    },
    {
      type: 2,
      group: "《警察和我之毒蛇帮》剧组",
      members: [
        {
          mark: "天放",
          avatar: "/members/2023-2024/help.webp",
          word: "Yes sir？你系条几？",
          duty: [0, 2, 3],
        },
        {
          mark: "署长傲天",
          avatar: "/members/2023-2024/huangsm.webp",
          word: "我，就是毒蛇帮的光！",
          duty: [12],
        },
        {
          mark: "师哥",
          avatar: "/members/2023-2024/guosh.webp",
          word: "Yes sir 不苟站岗，规章制度上墙。",
          duty: [12],
        },
        {
          mark: "大当家",
          avatar: "/members/2023-2024/diaojy.webp",
          word: "敢在我毒蛇帮做卧底，我看你是不想活了！",
          duty: [12],
        },
        {
          mark: "二当家",
          avatar: "/members/2023-2024/luzy.webp",
          word: "什么事这么好笑啊？",
          duty: [12],
        },
        {
          mark: "阿隋",
          avatar: "/members/2023-2024/sunzy.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《三块钱国币》剧组",
      members: [
        {
          mark: "杨长雄",
          avatar: "/members/2023-2024/liqm.webp",
          word: "这些无情的资本家不值得我们劳动人民同情！",
          duty: [0, 2, 3],
        },
        {
          mark: "吴太太",
          avatar: "/members/2023-2024/caidh.webp",
          word: "现在嘛，满嘴的假仁假义，以后啊，你就知道太太的好啦！",
          duty: [12],
        },
        {
          mark: "李嫂",
          avatar: "/members/2023-2024/baomc.webp",
          word: "太太，我没钱，我真是穷人！",
          duty: [12],
        },
        {
          mark: "成众",
          avatar: "/members/2023-2024/zhangcx.webp",
          word: "和棋！",
          duty: [12],
        },
        {
          mark: "警察",
          avatar: "/members/2023-2024/sunx.webp",
          word: "这还用说嘛！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《少爷和小姐》剧组",
      members: [
        {
          mark: "管家傲天",
          avatar: "/members/2023-2024/sunzy.webp",
          word: "龙傲在天上飞~",
          duty: [0, 2, 3],
        },
        {
          mark: "小霜",
          avatar: "/members/2023-2024/yangwy.webp",
          word: "霜儿在地上追~",
          duty: [12],
        },
        {
          mark: "赵娟er",
          avatar: "/members/2023-2024/geyn.webp",
          word: "我猜呀，你叫龙傲天，我呢，叫赵娟，哎，你不会就叫刘波吧？",
          duty: [12],
        },
        {
          mark: "刘波er",
          avatar: "/members/2023-2024/wangh.webp",
          word: "娟儿，我一见到你就有一种从未有过的感觉。",
          duty: [12],
        },
        {
          mark: "服务员",
          avatar: "/members/2023-2024/sunx.webp",
          word: "碰~瓷~儿~碰~瓷~儿~",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《花生瓜子》剧组",
      members: [
        {
          mark: "摸腿男",
          avatar: "/members/2023-2024/hongym.webp",
          word: "哎哟！龚正，你干嘛！~",
          duty: [0, 2, 3],
        },
        {
          mark: "偷包女",
          avatar: "/members/2023-2024/xiazt.webp",
          word: "现在的年轻人真是吹牛不打草稿的。",
          duty: [12],
        },
        {
          mark: "傻子",
          avatar: "/members/2023-2024/chenz.webp",
          word: "哈哈哈哈你马没了！",
          duty: [12],
        },
        {
          mark: "全场唯一真派",
          avatar: "/members/2023-2024/pengyy.webp",
          word: "遇到性骚扰， 我们绝对不能忍气吞声，不然这些流氓只会变本加厉！",
          duty: [12],
        },
        {
          mark: "海鲜粥",
          avatar: "/members/2023-2024/zhouyj.webp",
          word: "闺蜜，这你可就不懂了。",
          duty: [12],
        },
        {
          mark: "老婆大人",
          avatar: "/members/2023-2024/shux.webp",
          word: "你不是说我是你初恋吗？你给我解释清楚！",
          duty: [12],
        },
        {
          mark: "剽悍男",
          avatar: "/members/2023-2024/shijr.webp",
          word: "老龚，老龚~那你说怎么办吧？",
          duty: [12],
        },
        {
          mark: "龚正小律师",
          avatar: "/members/2023-2024/guost.webp",
          word: "肃静！！！现在看来啊，两边说的都有道理。",
          duty: [12],
        },
        {
          mark: "摊主",
          avatar: "/members/2023-2024/huangxy.webp",
          word: "花生瓜子，现炒现卖的花生瓜子嘞！",
          duty: [12],
        },
        {
          mark: "U盘守护者",
          avatar: "/members/2023-2024/guoyt.webp",
          word: "这唯一的证据。。。",
          duty: [12],
        },
      ],
    },
    {
      type: 1,
      group: "《你好疯子》剧组",
      members: [
        {
          mark: "Tom",
          avatar: "/members/2023-2024/tangbw1.webp",
          word: "你误会了，我们的意思是要从严处理你们的抗拒！",
          duty: [0, 2, 3],
        },
        {
          mark: "Benjamin",
          avatar: "/members/2023-2024/yangqc1.webp",
          word: "如果你不吃，我可以灌你吃；如果我今天灌你吃，那我以后他妈天天灌你吃！",
          duty: [0, 2, 3],
        },
        {
          mark: "Icy",
          avatar: "/members/2023-2024/chengx1.webp",
          word: "在天上的父，愿人们都尊称你的名为圣，愿你的旨意行在地上，如同行在天上。",
          duty: [12],
        },
        {
          mark: "Lily",
          avatar: "/members/2023-2024/gairy.webp",
          word: "你知道香奈儿粉红佳人配合帕米尔红酒那种微醺的奢靡吗？",
          duty: [5],
        },
        {
          mark: "Sam",
          avatar: "/members/2023-2024/xiawj1.webp",
          word: "先生我纠正一下，是精神病，不是神经病。",
          duty: [12],
        },
        {
          mark: "Shawn",
          avatar: "/members/2023-2024/xujn.webp",
          word: "为了防止破坏我们的运行秩序，讲话了，碾过去！",
          duty: [12],
        },
        {
          mark: "Sunny",
          avatar: "/members/2023-2024/zhangjs.webp",
          word: "真干净啊，干净得我他妈都脏了！",
          duty: [12],
        },
        {
          mark: "Lawrence",
          avatar: "/members/2023-2024/zhangcx1.webp",
          word: "对上帝的献祭是必须的！",
          duty: [12],
        },
        {
          mark: "He",
          avatar: "/members/2023-2024/herh.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "灵活的主持人",
          avatar: "/members/2023-2024/shijr1.webp",
          word: "",
          duty: [6],
        },
      ],
    },
    {
      type: 1,
      group: "《告白之夜2024·春》台前幕后",
      members: [
        {
          mark: "dushck",
          avatar: "/members/2023-2024/liqm1.webp",
          word: "话剧社是我的心血，中间忘了，所以我们真的都是这么好的人吗？",
          duty: [0, 2, 7],
        },
        {
          mark: "珠海发哥",
          avatar: "/members/2023-2024/zhuhf.webp",
          word: "这个，就叫专业！",
          duty: [0, 9],
        },
        {
          mark: "郭哥",
          avatar: "/members/2023-2024/guosh1.webp",
          word: "没用的消息大家都先撤回了吧。",
          duty: [0],
        },
        {
          mark: "He",
          avatar: "/members/2023-2024/herh.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "菜菜",
          avatar: "/members/2023-2024/caidh1.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "冷静",
          avatar: "/members/2023-2024/chenz1.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "橘子姐",
          avatar: "/members/2023-2024/diaojy1.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "Viyian",
          avatar: "/members/2023-2024/guost.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "超级大壳",
          avatar: "/members/2023-2024/huangsm2.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "杏花微雨",
          avatar: "/members/2023-2024/wangyh.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "海鲜粥",
          avatar: "/members/2023-2024/zhouyj1.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "小夏",
          avatar: "/members/2023-2024/xiazt1.webp",
          word: "",
          duty: [6],
        },
        {
          mark: "小钟",
          avatar: "/members/2023-2024/zhongqy1.webp",
          word: "",
          duty: [6],
        },
        {
          mark: "夏思鲤",
          avatar: "/members/2023-2024/lizq.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "妍姐",
          avatar: "/members/2023-2024/gaoy.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "铁狼",
          avatar: "/members/2023-2024/wanghj.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "幕后黑手",
          avatar: "/members/2023-2024/xiawj.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "gyn",
          avatar: "/members/2023-2024/geyn.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "元哥",
          avatar: "/members/2023-2024/luzy1.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "Page",
          avatar: "/members/2023-2024/help.webp",
          word: "",
          duty: [9],
        },
      ],
    },
    {
      type: 2,
      group: "《一出不好戏》剧组",
      members: [
        {
          mark: "粥导",
          avatar: "/members/2023-2024/zhouyj1.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "无雪",
          avatar: "/members/2023-2024/huangsj.webp",
          word: "",
          duty: [2],
        },
        {
          mark: "小红帽",
          avatar: "/members/2023-2024/huangsm2.webp",
          word: "他是来自北方的狼~",
          duty: [12],
        },
        {
          mark: "大灰狼",
          avatar: "/members/2023-2024/wangds.webp",
          word: "走在森林的小路上~",
          duty: [12],
        },
        {
          mark: "猎人",
          avatar: "/members/2023-2024/chenyd.webp",
          word: "万物皆可甜宠！",
          duty: [12],
        },
        {
          mark: "外婆",
          avatar: "/members/2023-2024/guosh1.webp",
          word: "改变不是乱编，细说不是胡说，你们这么改，是要给格林兄弟谢罪的。",
          duty: [12],
        },
        {
          mark: "总监",
          avatar: "/members/2023-2024/xuez.webp",
          word: "喜剧的结尾，不把观众弄哭，就不叫好喜剧！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《赵氏孤儿》剧组",
      members: [
        {
          mark: "程婴",
          avatar: "/members/2023-2024/hongym1.webp",
          word: "记着，你永远是赵氏孤儿！",
          duty: [0, 2, 3],
        },
        {
          mark: "庄姬",
          avatar: "/members/2023-2024/pengyy1.webp",
          word: "万籁俱寂，生者已死，死者涣散~",
          duty: [0],
        },
        {
          mark: "韩厥",
          avatar: "/members/2023-2024/zhangjs1.webp",
          word: "人生得一君子，足矣！",
          duty: [0],
        },
        {
          mark: "卫兵甲",
          avatar: "/members/2023-2024/huangsj1.webp",
          word: "箱中可有夹带？！",
          duty: [12],
        },
        {
          mark: "卫兵乙",
          avatar: "/members/2023-2024/sunzy1.webp",
          word: "箱中可有夹带？！",
          duty: [12],
        },
        {
          mark: "卫兵丙",
          avatar: "/members/2023-2024/guoyt2.webp",
          word: "箱中可有夹带？！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《警察和我》剧组",
      members: [
        {
          mark: "老大爷",
          avatar: "/members/2023-2024/shenhq1.webp",
          word: "没事儿，大爷这个……好久没这么开心过了，大爷先回家冷静冷静吧去！",
          duty: [0, 2, 3],
        },
        {
          mark: "妍姐",
          avatar: "/members/2023-2024/gaoy.webp",
          word: "",
          duty: [2],
        },
        {
          mark: "傲天",
          avatar: "/members/2023-2024/jinzy.webp",
          word: "当警察的早就准备好这一天了！",
          duty: [12],
        },
        {
          mark: "师哥",
          avatar: "/members/2023-2024/tangq.webp",
          word: "优雅，真是优雅。",
          duty: [12],
        },
        {
          mark: "小姑娘",
          avatar: "/members/2023-2024/yangyn.webp",
          word: "这个是刚才让我填的表，您看一下。",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《打开打不开的窗》剧组",
      members: [
        {
          mark: "dushck",
          avatar: "/members/2023-2024/liqm1.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "小五",
          avatar: "/members/2023-2024/baomc1.webp",
          word: "如果我还是一棵树的话，我就朝着那里生长，生长！然后穿过它，让他听到我的声音！",
          duty: [12],
        },
        {
          mark: "大哥",
          avatar: "/members/2023-2024/fanl.webp",
          word: "你不要简单去看，你要去感受它。",
          duty: [12],
        },
        {
          mark: "老三",
          avatar: "/members/2023-2024/zhongqy.webp",
          word: "克拉昂丝，是假的！",
          duty: [12],
        },
        {
          mark: "老四",
          avatar: "/members/2023-2024/heyh.webp",
          word: "放肆！它是我们的镇馆之宝，是艺术的顶点！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《军师恋盟》剧组",
      members: [
        {
          mark: "至尊宝",
          avatar: "/members/2023-2024/wangh1.webp",
          word: "干嘛催呀，已经很快了，我又不是真的会法术。",
          duty: [0, 2, 3],
        },
        {
          mark: "小婉",
          avatar: "/members/2023-2024/diaojy1.webp",
          word: "姐妹姐妹姐妹，他扎到我心里来了，我想说，我想说，我要说出来呀!",
          duty: [12],
        },
        {
          mark: "凌峰",
          avatar: "/members/2023-2024/guoyt1.webp",
          word: "兄弟兄弟兄弟，她问到我脸上来了，我该怎么回答？我想说，我想说，我想说出来了!",
          duty: [12],
        },
        {
          mark: "管乐",
          avatar: "/members/2023-2024/chenz1.webp",
          word: "看我给你搏出一个未来！",
          duty: [12],
        },
        {
          mark: "维伊",
          avatar: "/members/2023-2024/shijr2.webp",
          word: "主公，你且稍坐，待微臣为你打出一片江山！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《鸣凤之死》剧组",
      members: [
        {
          mark: "汤老师",
          avatar: "/members/2023-2024/tangbw.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "清晏",
          avatar: "/members/2023-2024/liangqy.webp",
          word: "",
          duty: [1],
        },
        {
          mark: "鸣凤",
          avatar: "/members/2023-2024/caidh1.webp",
          word: "觉慧，你莫怪我，我要殉我的心！",
          duty: [12],
        },
        {
          mark: "觉慧",
          avatar: "/members/2023-2024/liuyax.webp",
          word: "鸣凤，我该向何方去寻你？",
          duty: [12],
        },
        {
          mark: "高老太爷",
          avatar: "/members/2023-2024/wangds1.webp",
          word: "外边儿的人在造反，咱自己家里也喂出了个目无尊长的白眼狼！",
          duty: [12],
        },
        {
          mark: "周氏",
          avatar: "/members/2023-2024/fanjl.webp",
          word: "鸣凤，你不要怨我。",
          duty: [12],
        },
        {
          mark: "冯乐山",
          avatar: "/members/2023-2024/shenhq.webp",
          word: "冯某绝不夺人所爱，全凭高老爷定夺。",
          duty: [12],
        },
        {
          mark: "婉儿",
          avatar: "/members/2023-2024/caoxy.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《减肥帮往事》剧组",
      members: [
        {
          mark: "一手打碟一手玩劫",
          avatar: "/members/2023-2024/yangqc.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "减肥帮帮主",
          avatar: "/members/2023-2024/guohy.webp",
          word: "凡我帮众，胆敢私自摄入糖、油、碳水化合物者，虽远必诛！",
          duty: [12],
        },
        {
          mark: "老八",
          avatar: "/members/2023-2024/yangz.webp",
          word: "大哥，我祖上都是健身教练，饿怕了。",
          duty: [12],
        },
        {
          mark: "老四",
          avatar: "/members/2023-2024/wangyh.webp",
          word: "大哥，没毛病！正常人说话，都这样！",
          duty: [12],
        },
        {
          mark: "土豆",
          avatar: "/members/2023-2024/zhangmk.webp",
          word: "大哥我是鸳鸯的啊！",
          duty: [12],
        },
        {
          mark: "严仔",
          avatar: "/members/2023-2024/zhangyx.webp",
          word: "我就算做普拉提也不会放过你的！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《小小世界的不速之客》剧组",
      members: [
        {
          mark: "Page",
          avatar: "/members/2023-2024/help.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "无名的人",
          avatar: "/members/2023-2024/luzy1.webp",
          word: "三心二心你心我心他心原本一心！何来分别三心二心？",
          duty: [12],
        },
        {
          mark: "乐队长",
          avatar: "/members/2023-2024/zhouyj1.webp",
          word: "知道就是知道，不知道就是不知道。道可道，非常道，听我说完，你可知道？",
          duty: [12],
        },
        {
          mark: "吉他手",
          avatar: "/members/2023-2024/duyw.webp",
          word: "微信还是支付宝？",
          duty: [12],
        },
        {
          mark: "三角铁",
          avatar: "/members/2023-2024/caimj.webp",
          word: "你得仰望星空，迎接你的就是星辰大海。",
          duty: [12],
        },
        {
          mark: "列车员",
          avatar: "/members/2023-2024/zhouyx.webp",
          word: "香烟啤酒火腿肠泡面！",
          duty: [12],
        },
      ],
    },
  ],
  [
    {
      type: 0,
      group: "社团负责人",
      members: [
        {
          mark: "铁狼",
          avatar: "/members/2024-2025/wanghj.webp",
          word: "",
          duty: [10],
        },
        {
          mark: "群书记",
          avatar: "/members/2024-2025/chenz.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "小帅",
          avatar: "/members/2024-2025/guosh1.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "全场唯一真派",
          avatar: "/members/2024-2025/pengyy.webp",
          word: "",
          duty: [11],
        },
        {
          mark: "海鲜粥",
          avatar: "/members/2024-2025/zhouyj.webp",
          word: "",
          duty: [11],
        },
      ],
    },
    {
      type: 1,
      group: "《告白之夜2024·秋》台前幕后",
      members: [
        {
          mark: "铁狼",
          avatar: "/members/2024-2025/wanghj.webp",
          word: "",
          duty: [0, 2, 7],
        },
        {
          mark: "He",
          avatar: "/members/2024-2025/herh.webp",
          word: "",
          duty: [4],
        },
        {
          mark: "阳照枝头",
          avatar: "/members/2024-2025/zengzz.webp",
          word: "",
          duty: [5, 7],
        },
        {
          mark: "海鲜粥",
          avatar: "/members/2024-2025/zhouyj1.webp",
          word: "",
          duty: [5, 7],
        },
        {
          mark: "妍姐",
          avatar: "/members/2024-2025/gaoy.webp",
          word: "",
          duty: [5, 8],
        },
        {
          mark: "小灯",
          avatar: "/members/2024-2025/chenyr.webp",
          word: "",
          duty: [5, 8],
        },
        {
          mark: "白线",
          avatar: "",
          word: "",
          duty: [5, 8],
        },
        {
          mark: "糊涂涂",
          avatar: "/members/2024-2025/tuy.webp",
          word: "",
          duty: [5, 8],
        },
        {
          mark: "九土",
          avatar: "/members/2024-2025/fangzy.webp",
          word: "",
          duty: [5],
        },
        {
          mark: "钟大夫",
          avatar: "/members/2024-2025/kongst.webp",
          word: "",
          duty: [5],
        },
        {
          mark: "汤老师",
          avatar: "/members/2024-2025/tangbw.webp",
          word: "",
          duty: [6],
        },
        {
          mark: "小帅",
          avatar: "/members/2024-2025/guosh1.webp",
          word: "",
          duty: [7],
        },
        {
          mark: "锦鲤",
          avatar: "/members/2024-2025/liqs.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "夏思鲤",
          avatar: "/members/2024-2025/lizq.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "元哥",
          avatar: "/members/2024-2025/luzy.webp",
          word: "",
          duty: [8],
        },
        {
          mark: "发哥",
          avatar: "/members/2024-2025/zhuhf.webp",
          word: "",
          duty: [9],
        },
        {
          mark: "dushck",
          avatar: "/members/2024-2025/liqm.webp",
          word: "",
          duty: [9],
        },
        {
          mark: "Page",
          avatar: "/members/2024-2025/help.webp",
          word: "",
          duty: [9],
        },
        {
          mark: "Viyian",
          avatar: "/members/2024-2025/guost.webp",
          word: "",
          duty: [9],
        },
      ],
    },
    {
      type: 2,
      group: "《八十一难》剧组",
      members: [
        {
          mark: "群书记",
          avatar: "/members/2024-2025/chenz1.webp",
          word: "封为金身罗汉。",
          duty: [0, 2, 3],
        },
        {
          mark: "悟净",
          avatar: "/members/2024-2025/zhangjs.webp",
          word: "师父，我可以当妖怪！可是，我不能伤害你呀！",
          duty: [12],
        },
        {
          mark: "三藏",
          avatar: "/members/2024-2025/daiab.webp",
          word: "终一生度世人，和终一世度一人，为师觉得是一样的。",
          duty: [12],
        },
        {
          mark: "悟空",
          avatar: "/members/2024-2025/wangds.webp",
          word: "人善，就不该被人骑！",
          duty: [12],
        },
        {
          mark: "八戒",
          avatar: "/members/2024-2025/oumj.webp",
          word: "他又不像你那么厉害，也不像师父有背景，更不像我，长得那么帅。",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《我们的荆轲》剧组",
      members: [
        {
          mark: "曾导",
          avatar: "/members/2024-2025/zengzz.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "清晏",
          avatar: "/members/2024-2025/liangqy.webp",
          word: "",
          duty: [1],
        },
        {
          mark: "荆轲",
          avatar: "/members/2024-2025/yanghx.webp",
          word: "我，为侠士的荣誉刺你！",
          duty: [12],
        },
        {
          mark: "燕姬",
          avatar: "/members/2024-2025/caoxy.webp",
          word: "如果汤里煲的是一条狗腿呢？",
          duty: [12],
        },
        {
          mark: "太子丹",
          avatar: "/members/2024-2025/yangqc.webp",
          word: "嬴政啊嬴政，我仿佛看到了你的末日！",
          duty: [12],
        },
        {
          mark: "秦舞阳",
          avatar: "/members/2024-2025/wanghj1.webp",
          word: "土包子怎么了？",
          duty: [12],
        },
        {
          mark: "狗屠",
          avatar: "/members/2024-2025/wangjy.webp",
          word: "想我大燕有成片的原始森林。",
          duty: [12],
        },
        {
          mark: "秦王",
          avatar: "/members/2024-2025/xuzh.webp",
          word: "我们，历史上见！",
          duty: [12],
        },
        {
          mark: "高渐离",
          avatar: "/members/2024-2025/zhangcx.webp",
          word: "侠肝，义胆，美人血！",
          duty: [12],
        },
        {
          mark: "刘亚迪",
          avatar: "",
          word: "大王负剑！大王负剑！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《心动的信号》剧组",
      members: [
        {
          mark: "全场唯一真派",
          avatar: "/members/2024-2025/pengyy1.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "大当家",
          avatar: "/members/2024-2025/zhangsh.webp",
          word: "爸，您终于认可我了！",
          duty: [12],
        },
        {
          mark: "二当家",
          avatar: "/members/2024-2025/luoy.webp",
          word: "爸，你喝啥？",
          duty: [12],
        },
        {
          mark: "三当家",
          avatar: "/members/2024-2025/gengqy.webp",
          word: "爸，大哥儿子被学校开除了。",
          duty: [12],
        },
        {
          mark: "弟妹",
          avatar: "/members/2024-2025/wangyh.webp",
          word: "阿萨迪，阿萨哆。",
          duty: [12],
        },
        {
          mark: "坤叔",
          avatar: "/members/2024-2025/shenhq.webp",
          word: "老东西，在那边等着，等我下去咱俩接着斗。",
          duty: [12],
        },
        {
          mark: "高超",
          avatar: "/members/2024-2025/yinzy.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "高越",
          avatar: "/members/2024-2025/huj.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "医生",
          avatar: "/members/2024-2025/shijr.webp",
          word: "捐点二当家有的东西吧！",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《请你对我说个谎》剧组",
      members: [
        {
          mark: "马通",
          avatar: "/members/2024-2025/guosh1.webp",
          word: "亲情，我和她是亲情！我和你，才是真正的爱情~",
          duty: [0, 2, 3],
        },
        {
          mark: "桃乐丝白",
          avatar: "/members/2024-2025/baomc.webp",
          word: "我叫桃乐丝，我想好好谈一场恋爱。",
          duty: [12],
        },
        {
          mark: "桃乐丝蓝",
          avatar: "/members/2024-2025/gairy.webp",
          word: "我叫桃乐丝，我只想好好谈一场恋爱，但是他已经结婚了。",
          duty: [12],
        },
        {
          mark: "桃乐丝红",
          avatar: "/members/2024-2025/weimy.webp",
          word: "我叫桃乐丝，我只想好好谈一场恋爱，虽然他已经结婚了，但是我们已经交往一年多了。",
          duty: [12],
        },
        {
          mark: "钟大夫",
          avatar: "/members/2024-2025/kongst1.webp",
          word: "我应该生活得很好，我应该放弃这段鸡肋的婚姻，我会过得很幸福。",
          duty: [12],
        },
      ],
    },
    {
      type: 1,
      group: "《告白之夜2025·春》台前幕后",
      members: [
        {
          mark: "铁狼",
          avatar: "/members/2024-2025/wanghj.webp",
          word: "",
          duty: [0, 2, 7],
        },
      ],
    },
    {
      type: 2,
      group: "《披星戴月的想你》剧组",
      members: [
        {
          mark: "小孔",
          avatar: "/members/2024-2025/kongst2.webp",
          word: "我打死你！",
          duty: [0, 2, 3],
        },
        {
          mark: "小杰",
          avatar: "/members/2024-2025/oumj1.webp",
          word: "对不起，我忘了。",
          duty: [12],
        },
        {
          mark: "小霂",
          avatar: "/members/2024-2025/weimy1.webp",
          word: "没事儿。",
          duty: [12],
        },
        {
          mark: "小陈",
          avatar: "/members/2024-2025/chenh.webp",
          word: "百年好合~",
          duty: [12],
        },
        {
          mark: "小涵",
          avatar: "/members/2024-2025/herh1.webp",
          word: "我是美作",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《电子烟灰》剧组",
      members: [
        {
          mark: "月半衔蝉",
          avatar: "/members/2024-2025/zhangcx1.webp",
          word: "为了戏剧，不顾明天；因为戏剧，还有明天。",
          duty: [0, 2, 3],
        },
        {
          mark: "小白",
          avatar: "/members/2024-2025/gaoy1.webp",
          word: "你说在网络世界，一个人被删除是不是就等于死亡？",
          duty: [12],
        },
        {
          mark: "电子",
          avatar: "/members/2024-2025/baomc1.webp",
          word: "遗忘不是一种记忆的失败，而是一种记忆的功能。",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《民国往事》剧组",
      members: [
        {
          mark: "向晚",
          avatar: "",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "句宝盆",
          avatar: "/members/2024-2025/wangjy1.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "句夫人",
          avatar: "/members/2024-2025/liyh.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "于堂主",
          avatar: "/members/2024-2025/gengqy1.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "于小妹",
          avatar: "/members/2024-2025/lizt.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "老板",
          avatar: "/members/2024-2025/yanghx1.webp",
          word: "",
          duty: [12],
        },
      ],
    },
    {
      type: 2,
      group: "《恋爱的犀牛》剧组",
      members: [
        {
          mark: "红红",
          avatar: "/members/2024-2025/pengyy2.webp",
          word: "",
          duty: [0, 2, 3],
        },
        {
          mark: "马路",
          avatar: "/members/2024-2025/guosh2.webp",
          word: "黄昏是我一天中视力最差的时候，一眼望去满街都是美女。",
          duty: [12],
        },
        {
          mark: "明明",
          avatar: "/members/2024-2025/gairy1.webp",
          word: "人是可以在二氧化碳里呼吸的，只要有爱情。",
          duty: [12],
        },
        {
          mark: "黑子",
          avatar: "",
          word: "",
          duty: [12],
        },
        {
          mark: "大仙",
          avatar: "",
          word: "",
          duty: [12],
        },
        {
          mark: "牙刷",
          avatar: "/members/2024-2025/wangh.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "莉莉",
          avatar: "/members/2024-2025/tuy1.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "经纪人",
          avatar: "/members/2024-2025/chenyr1.webp",
          word: "",
          duty: [12],
        },
        {
          mark: "摄影师",
          avatar: "/members/2024-2025/zhouyx.webp",
          word: "",
          duty: [12],
        },
      ],
    },
  ],
];

export default members;
