const shows = [
  [
    {
      title: "戏中戏中戏",
      cover: "/shows/xzxzx/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "时间长河滚滚，记忆星光寥落。欢迎回到2015年，告白剧社梦开始的地方。",
        },
        {
          type: "text",
          content: "本作品为剧社原创的小品，也是剧社登台的第一个作品。",
        },
        { type: "image", url: "/shows/xzxzx/001.webp", caption: "" },
        { type: "image", url: "/shows/xzxzx/002.webp", caption: "" },
        { type: "image", url: "/shows/xzxzx/003.webp", caption: "" },
      ],
    },
  ],
  [
    {
      title: "你好，打劫",
      cover: "/shows/nhdj/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "欢迎回来，我的老朋友，这里是2017年，《你好，打劫》的演出现场。",
        },
        {
          type: "text",
          content:
            "作品翻演自饶晓志导演、一柏编剧的先锋话剧，作为剧社首个年度大戏，在F栋报告厅演出。",
        },
        { type: "image", url: "/shows/nhdj/001.webp", caption: "" },
        { type: "image", url: "/shows/nhdj/002.webp", caption: "" },
        { type: "image", url: "/shows/nhdj/003.webp", caption: "" },
        { type: "image", url: "/shows/nhdj/004.webp", caption: "" },
        { type: "image", url: "/shows/nhdj/005.webp", caption: "" },
        { type: "image", url: "/shows/nhdj/006.webp", caption: "" },
        { type: "image", url: "/shows/nhdj/007.webp", caption: "" },
      ],
    },
  ],
  [
    {
      title: "暗恋·桃花源",
      cover: "/shows/althy/cover.webp",
      contents: [
        {
          type: "text",
          content: "欢迎回到2018年，这里是《暗恋·桃花源》的演出现场。",
        },
        {
          type: "text",
          content:
            "作品翻演自赖声川经典话剧《暗恋·桃花源》，作为剧社年度大戏，在F栋报告厅演出。",
        },
        { type: "image", url: "/shows/althy/001.webp", caption: "" },
        { type: "image", url: "/shows/althy/002.webp", caption: "" },
        { type: "image", url: "/shows/althy/003.webp", caption: "" },
        { type: "image", url: "/shows/althy/004.webp", caption: "" },
        { type: "image", url: "/shows/althy/005.webp", caption: "" },
        { type: "image", url: "/shows/althy/006.webp", caption: "" },
        { type: "image", url: "/shows/althy/007.webp", caption: "" },
        { type: "image", url: "/shows/althy/008.webp", caption: "" },
        { type: "image", url: "/shows/althy/009.webp", caption: "" },
        { type: "image", url: "/shows/althy/010.webp", caption: "" },
        { type: "image", url: "/shows/althy/011.webp", caption: "" },
        { type: "image", url: "/shows/althy/012.webp", caption: "" },
        { type: "image", url: "/shows/althy/013.webp", caption: "" },
        { type: "image", url: "/shows/althy/014.webp", caption: "" },
        { type: "image", url: "/shows/althy/015.webp", caption: "" },
        { type: "image", url: "/shows/althy/016.webp", caption: "" },
        { type: "image", url: "/shows/althy/017.webp", caption: "" },
        { type: "image", url: "/shows/althy/018.webp", caption: "" },
        { type: "image", url: "/shows/althy/019.webp", caption: "" },
        { type: "image", url: "/shows/althy/020.webp", caption: "" },
        { type: "image", url: "/shows/althy/021.webp", caption: "" },
        { type: "image", url: "/shows/althy/022.webp", caption: "" },
        { type: "image", url: "/shows/althy/023.webp", caption: "" },
        { type: "image", url: "/shows/althy/024.webp", caption: "" },
        { type: "image", url: "/shows/althy/025.webp", caption: "" },
        { type: "image", url: "/shows/althy/026.webp", caption: "" },
        { type: "image", url: "/shows/althy/027.webp", caption: "" },
        { type: "image", url: "/shows/althy/028.webp", caption: "" },
        { type: "image", url: "/shows/althy/029.webp", caption: "" },
        { type: "image", url: "/shows/althy/030.webp", caption: "" },
      ],
    },
  ],
  [
    {
      title: "乌龙山伯爵",
      cover: "/shows/wlsbj/cover.webp",
      contents: [
        {
          type: "text",
          content: "欢迎回到2019年5月，这里是《乌龙山伯爵》的演出现场。",
        },
        {
          type: "text",
          content:
            "作品翻演自开心麻花经典喜剧《乌龙山伯爵》，作为剧社年度大戏，在F栋报告厅演出。",
        },
        { type: "image", url: "/shows/wlsbj/000.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/001.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/002.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/003.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/004.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/005.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/006.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/007.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/008.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/009.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/010.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/011.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/012.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/013.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/014.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/015.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/016.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/017.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/018.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/019.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/020.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/021.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/022.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/023.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/024.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/025.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/026.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/027.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/028.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/029.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/030.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/031.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/032.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/033.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj/034.webp", caption: "" },
      ],
    },
  ],
  [
    {
      title: "迎新专场——乌龙山伯爵",
      cover: "/shows/wlsbj2/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "是的，我们又排了一次《乌龙山伯爵》，欢迎回到2019年9月开学季，这里是迎新专场。",
        },
        { type: "image", url: "/shows/wlsbj2/000.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/001.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/002.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/003.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/004.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/005.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/006.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/007.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/008.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/009.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/010.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/011.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/012.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/013.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/014.webp", caption: "" },
        { type: "image", url: "/shows/wlsbj2/015.webp", caption: "" },
      ],
    },
    {
      title: "告白之夜2019",
      cover: "/shows/gb2019/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "现在是2019年11月的最后一个夜晚，我们相聚在F栋报告厅。为了首次《告白之夜》短剧专场的顺利演出，我们准备了六周。",
        },
        {
          type: "text",
          content:
            "这次演出包含四个作品。《从前有座山》翻演自上海外国语大学飞那儿剧团的原创作品，讲述了小和尚下山游历，通过实践和思考，对抗老方丈的精神枷锁，从而实现人格独立的故事。《金陵十三钗》改编自严歌苓同名著作，书写战火中女性互助的壮烈悲歌。《潜伏》翻演自声临其境第一季同名配音作品，还原录音事件的精彩桥段。《聂耳小提琴的前世传奇》翻演自国家宝藏第二季短剧节目，讲述了聂耳与狱中田汉惺惺相惜遥相呼应，共同谱写《义勇军进行曲》的传奇故事。",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1fJ411Q757/",
          caption: "从前有座山",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1ZJ411Q7qy/",
          caption: "金陵十三钗",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1rJ411B78Z/",
          caption: "聂耳小提琴的前世传奇、潜伏",
        },
        { type: "image", url: "/shows/gb2019/000.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/001.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/002.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/003.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/004.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/005.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/006.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/007.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/008.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/009.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/010.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/011.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/012.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/013.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/014.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/015.webp", caption: "" },
        { type: "image", url: "/shows/gb2019/016.webp", caption: "" },
      ],
    },
    {
      title: "校元旦晚会——聂耳小提琴的前世传奇",
      cover: "/shows/xtqyd/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "现在是2019年末，《聂耳小提琴的前世传奇》登上校元旦晚会的舞台。",
        },
        { type: "image", url: "/shows/xtqyd/000.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/001.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/002.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/003.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/004.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/005.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/006.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/007.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/008.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/009.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/010.webp", caption: "" },
        { type: "image", url: "/shows/xtqyd/011.webp", caption: "" },
      ],
    },
  ],
  [
    {
      title: "校元旦晚会——金漆雕木大神龛",
      cover: "/shows/sk/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "现在是2020年末，《金漆雕木大神龛》登上校元旦晚会的舞台。该作品翻演自国家宝藏第一季的短剧节目，讲述了在战争年代，南洋从商的哥哥陈卓想要带弟弟陈凡远离战火，而弟弟决定保家卫国慷慨赴义的故事。",
        },
      ],
    },
    {
      title: "告白之夜2021",
      cover: "/shows/gb2021/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "这里是2021年5月22日晚的F栋报告厅，《告白之夜2021》正在上演。",
        },
        {
          type: "text",
          content:
            "这次演出包含五个作品。《9102》翻演自上海外国语大学飞那儿剧团的原创作品，通过描写科研产品9102在重复工作生活中逐渐觉醒自我意识，表达了对极致效率、极致功利的反思。《压迫》翻演自丁西林作品，以房东母女两人在租房问题上的不同意见为基础展开，揭露了当时社会有房者和无房者之间的矛盾。《酒后》翻演自丁西林作品，以一位朋友酒后醉卧为引子，将一对夫妻的朦胧爱意展示得淋漓尽致。《金漆雕木大神龛》翻演自国家宝藏第一季的短剧节目，讲述了在战争年代，南洋从商的哥哥陈卓想要带弟弟陈凡远离战火，而弟弟决定保家卫国慷慨赴义的故事。《鸡兔同笼》翻演自第七届乌镇戏剧节刘添祺作品，展现了狱中父亲和年幼女儿的深厚亲情。",
        },
        { type: "image", url: "/shows/gb2021/000.webp", caption: "" },
        { type: "image", url: "/shows/gb2021/001.webp", caption: "" },
        { type: "image", url: "/shows/gb2021/002.webp", caption: "" },
        { type: "image", url: "/shows/gb2021/003.webp", caption: "" },
        { type: "image", url: "/shows/gb2021/004.webp", caption: "" },
        { type: "image", url: "/shows/gb2021/005.webp", caption: "" },
        { type: "image", url: "/shows/gb2021/006.webp", caption: "" },
        { type: "image", url: "/shows/gb2021/007.webp", caption: "" },
        { type: "image", url: "/shows/gb2021/008.webp", caption: "" },
        { type: "image", url: "/shows/gb2021/009.webp", caption: "" },
      ],
    },
  ],
  [
    {
      title: "理学院迎新晚会——点名风波",
      cover: "/shows/dmfb/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "这里是2021年末的理学院迎新晚会，《点名风波》登上活动中心的舞台。该作品是由剧社同学『如如』原创，呈现了一场幽默生动的课堂点名闹剧。",
        },
      ],
    },
    {
      title: "计科元旦晚会——觉醒年代",
      cover: "/shows/jxnd/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "这里是2021年末的计算机科学与技术学院元旦晚会，《觉醒年代》登上活动中心的舞台。该作品是由剧社多位同学联合创作，改编自热播电视剧《觉醒年代》，以陈延年为主线，集中展现了当时青年革命者从思想到实践最终升华为信仰的革命过程，弘扬大无畏的革命斗争精神。",
        },
      ],
    },
    {
      title: "毕业小戏——谁杀死了周日",
      cover: "/shows/ssslzr/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "现在是2022年的夏天，剧社中即将毕业的同学打算过把戏瘾，翻演了喜剧大赛第一季作品《谁杀死了周日》。很遗憾，因为一些原因没有登上深圳校区20周年晚会的舞台，但是在F栋报告厅录制了一个版本。",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1N94y1D7tF/",
          caption: "",
        },
      ],
    },
  ],
  [
    {
      title: "校迎新晚会——谁杀死了周日",
      cover: "/shows/ssslzr2/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "这里是2022年9月的校迎新晚会，在哈工大田径场搭了个露天舞台。依稀记得那天下着小雨。新剧组带着《谁杀死了周日》重回舞台，也算弥补了6月的遗憾。",
        },
        { type: "image", url: "/shows/ssslzr2/000.webp", caption: "" },
        { type: "image", url: "/shows/ssslzr2/001.webp", caption: "" },
        { type: "image", url: "/shows/ssslzr2/002.webp", caption: "" },
        { type: "image", url: "/shows/ssslzr2/003.webp", caption: "" },
        { type: "image", url: "/shows/ssslzr2/004.webp", caption: "" },
        { type: "image", url: "/shows/ssslzr2/005.webp", caption: "" },
        { type: "image", url: "/shows/ssslzr2/006.webp", caption: "" },
        { type: "image", url: "/shows/ssslzr2/007.webp", caption: "" },
      ],
    },
    {
      title: "告白之夜2023·春",
      cover: "/shows/gb2023/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "欢迎回到2023年5月21日晚，《告白之夜2023·春》正在F栋报告厅上演。",
        },
        {
          type: "text",
          content:
            "演出包含四个作品。《青铜仙鹤》翻演自国家宝藏第三季的短剧节目，以鹤为引，讲述了嬴政与燕太子丹截然不同的命运。《时间都去哪儿了》翻演自喜剧大赛第一季作品，通过将主流社交APP人格化，精准诙谐地刻画了手机占据太多时间的现象。《瞎了一只眼》翻演自丁西林作品，描写了因一封言辞夸张的信件，夫妇共同对前来探望的朋友圆谎，上演一段另类“扒马褂”的故事。《风声》改编自《风声》原著和网剧，呈现了一场恐怖压抑、可歌可泣的谍战风云。",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1js4y1T7da/",
          caption: "全场回放",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV111421i7hM/",
          caption: "青铜仙鹤",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1my411a7Mj/",
          caption: "时间都去哪儿了",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV19D421G7fk/",
          caption: "瞎了一只眼",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1PU411Z7Qh/",
          caption: "风声",
        },
        { type: "image", url: "/shows/gb2023/000.webp", caption: "" },
        { type: "image", url: "/shows/gb2023/001.webp", caption: "" },
        { type: "image", url: "/shows/gb2023/002.webp", caption: "" },
        { type: "image", url: "/shows/gb2023/003.webp", caption: "" },
        { type: "image", url: "/shows/gb2023/004.webp", caption: "" },
        { type: "image", url: "/shows/gb2023/005.webp", caption: "" },
        { type: "image", url: "/shows/gb2023/006.webp", caption: "" },
        { type: "image", url: "/shows/gb2023/007.webp", caption: "" },
      ],
    },
  ],
  [
    {
      title: "告白之夜2023·秋",
      cover: "/shows/gb20232/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "欢迎回到2023年12月02日晚，《告白之夜2023·秋》正在F栋报告厅上演。",
        },
        {
          type: "text",
          content:
            "这次演出包含四个作品。《警察和我之蛇我其谁》翻演自喜剧大赛，讲述了十年卧底师哥与警长师弟默契配合，联手将毒蛇帮一网打尽的故事。《三块钱国币》翻演自丁西林作品，描写大学生租客杨长雄与女房东吴太太围绕女仆李嫂该不该为不慎打破的一只花瓶赔钱而展开激烈的争辩。《少爷和小姐》翻演自喜剧大赛第二季作品，诠释酣畅淋漓的玛丽苏爱情。《花生瓜子》翻演自上海海事大学子兮话剧社原创作品，通过摸腿男和偷包女的冲突展开一系列社会乱象。",
        },
        { type: "image", url: "/shows/gb20232/000.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/001.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/002.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/003.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/004.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/005.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/006.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/007.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/008.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/009.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/010.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/011.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/012.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/013.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/014.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/015.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/016.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/017.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/018.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/019.webp", caption: "" },
        { type: "image", url: "/shows/gb20232/020.webp", caption: "" },
      ],
    },
    {
      title: "你好，疯子",
      cover: "/shows/nhfz/000.webp",
      contents: [
        {
          type: "text",
          content:
            "欢迎回到2024年05月12日的下午，我们相聚在桃源文体站一楼演出厅，共同欣赏饶晓志话剧作品《你好，疯子》。",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV16i421X7mM",
          caption: "你好，疯子",
        },
        { type: "image", url: "/shows/nhfz/000.webp", caption: "" },
        { type: "image", url: "/shows/nhfz/001.webp", caption: "" },
        { type: "image", url: "/shows/nhfz/002.webp", caption: "" },
        { type: "image", url: "/shows/nhfz/003.webp", caption: "" },
        { type: "image", url: "/shows/nhfz/004.webp", caption: "" },
        { type: "image", url: "/shows/nhfz/005.webp", caption: "" },
        { type: "image", url: "/shows/nhfz/006.webp", caption: "" },
        { type: "image", url: "/shows/nhfz/007.webp", caption: "" },
      ],
    },
    {
      title: "告白之夜2024·春",
      cover: "/shows/gb2024/000.webp",
      contents: [
        {
          type: "text",
          content:
            "这里是2024年5月的第三个周末，《告白之夜2024·春》正在F栋报告厅上演。",
        },
        {
          type: "text",
          content:
            "演出持续了两个夜晚、共计八个作品。《一出不好戏》翻演自喜剧大赛第一季作品，辛辣讽刺了影视文艺行业的乱象。《赵氏孤儿》翻演自演员的诞生第一季作品，讲述东周三晋往事时，意外产生了不错的喜剧效果。《警察与我》翻演自喜剧大赛第二季作品，讲述了卧底师哥回归警局后的一系列趣事。《打开打不开的窗》翻演自2023年乌镇戏剧节青赛入围作品，意识流地表达了冲破、追寻真我的思想。《军师恋盟》翻演自喜剧大赛第二季作品，生动有趣地刻画了有情人爱在心头口难开的场景。《鸣凤之死》节选改编自话剧《家》，讲述了一个封建压迫下底层人民的悲剧。《减肥帮往事》翻演自喜剧大赛第二季作品，以夸张的方式戏谑了过度减肥的现象。《小小世界的不速之客》翻演自2023年乌镇戏剧节青赛入围作品，意识流地探讨了物质欲望和精神追求的关系，该人带来禅性的深思。",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1EE421F7ix/",
          caption: "演出第一晚合集",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1ND421V7Df/",
          caption: "演出第二晚合集",
        },
        { type: "image", url: "/shows/gb2024/000.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/001.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/002.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/003.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/004.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/005.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/006.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/007.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/008.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/009.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/010.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/011.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/012.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/013.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/014.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/015.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/016.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/017.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/018.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/019.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/020.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/021.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/022.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/023.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/024.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/025.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/026.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/027.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/028.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/029.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/030.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/031.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/032.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/033.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/034.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/035.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/036.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/037.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/038.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/039.webp", caption: "" },
        { type: "image", url: "/shows/gb2024/040.webp", caption: "" },
      ],
    },
  ],
  [
    {
      title: "告白之夜2024·秋",
      cover: "/shows/gb20242/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "这里是2024年12月08日的夜晚，《告白之夜2024·秋》正在F栋报告厅上演。",
        },
        {
          type: "text",
          content:
            "演出包含四个作品。《八十一难》翻演自喜人奇妙夜作品，从沙僧的视角重写取经项目的故事。《我们的荆轲》节选自北京人艺同名话剧作品，从名利、侠义、公心、私情等多角度，重新解构荆轲刺秦的内核。《心动的信号》翻演自喜人奇妙夜作品，展现了西西里里家族的温情。《请你对我说个谎》节选自林蔚然同名话剧作品，探讨了爱情、婚姻、伦理等问题。",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1kNqmYvEHE",
          caption: "八十一难、我们的荆轲、心动的信号",
        },
        {
          type: "video",
          url: "https://www.bilibili.com/video/BV1Xkq2YnEAr",
          caption: "请你对我说个谎",
        },
        { type: "image", url: "/shows/gb20242/000.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/100.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/101.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/102.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/103.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/104.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/105.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/106.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/107.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/200.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/201.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/202.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/203.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/204.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/205.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/206.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/207.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/300.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/301.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/302.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/303.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/304.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/400.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/401.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/402.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/403.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/404.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/405.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/500.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/501.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/502.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/503.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/504.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/600.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/601.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/602.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/603.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/604.webp", caption: "" },
        { type: "image", url: "/shows/gb20242/605.webp", caption: "" },
      ],
    },
    {
      title: "告白之夜2025·春",
      cover: "/shows/gb2025/cover.webp",
      contents: [
        {
          type: "text",
          content:
            "这里是2025年06月08日的夜晚，《告白之夜2025·春》正在F栋报告厅上演。尽管排练仓促，只在演出前一晚和演出当天上午各彩排了一次，但在大家的齐心努力下，我们依旧呈现出一场完美的演出。",
        },
        {
          type: "text",
          content:
            "演出包含四个作品。《披星戴月的想你》翻演自喜剧大赛S1作品，为皓史成双CP划上完整的句号。《电子烟灰》翻演自乌镇青赛2021、北国剧社作品，通过人死后灵魂可以进入赛博空间的设定，探索真实生活与网络空间的边界。《民国往事》翻演自欢乐集结号作品，讲述了孙媳妇通过时空穿越拯救爷爷的有趣故事。《恋爱的犀牛》节选自廖一梅话剧作品，保留了马路和明明的故事主线，生动刻画了一场轰轰烈烈的、因爱伤人为爱自伤的爱情悲剧。",
        },
        // {
        //   type: "video",
        //   url: "https://www.bilibili.com/video/BV1kNqmYvEHE",
        //   caption: "八十一难、我们的荆轲、心动的信号",
        // },
        // {
        //   type: "video",
        //   url: "https://www.bilibili.com/video/BV1Xkq2YnEAr",
        //   caption: "请你对我说个谎",
        // },
        { type: "image", url: "/shows/gb2025/000.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/001.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/100.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/101.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/102.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/103.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/104.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/105.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/200.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/201.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/202.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/203.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/204.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/300.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/301.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/302.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/303.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/400.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/401.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/402.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/403.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/404.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/405.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/500.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/501.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/502.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/503.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/504.webp", caption: "" },
        { type: "image", url: "/shows/gb2025/505.webp", caption: "" },
      ],
    },
  ],
].reverse();

export default shows;
